### ISSUE TITLE
error installing RelStorage

### ISSUE THREAD

**Issue by tkimnguyen** [collective/training-sandbox#2]
Getting an error installing RelStorage 2.0.0 (twice in a row just now)

The buildpack URL is https://github.com/plone/heroku-buildpack-plone#5.0.6

```
-----> Plone app detected
-----> Use build cache
       Cache empty, let's fix that
       Prime with Unified Installer cache
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0:23:06  248k  7 58.1M    7 4557k    0     0   180k      0  0:05:29  0:00:25  0:05:04  205k 0     0   250k      0  0:03:58  0:00:54  0:03:04  243k  0     0   249k      0  0:03:58  0:00:57  0:03:01  244k24 58.1M   24 14.2M    0     0   250k      0  0:03:58  0:00:58  0:03:00  248k 0   400k      0  0:02:28  0:01:13  0:01:15 2329k
       Unpacking Installer
       Unpacking Installer cache
       Moving cache eggs to build directory
       Clean up Installer files
-----> Read BUILDOUT_CFG from env vars, or use default
       Using default: heroku.cfg
-----> Read BUILDOUT_VERBOSITY from env vars, or use default
       Use default buildout verbosity
-----> Read BOOTSTRAP_PY_URL from env vars, or use default
       Use default bootstrap.py: http://downloads.buildout.org/2/bootstrap.py
-----> Bootstrap buildout
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
curl: (6) Could not resolve host: L
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="https://bootstrap.pypa.io/bootstrap-buildout.py">here</a>.</p>
<hr>
<address>Apache Server at downloads.buildout.org Port 80</address>
</body></html>
Downloading https://pypi.io/packages/source/s/setuptools/setuptools-32.3.0.zip
Extracting in /tmp/tmpyTm0Pa
Now working in /tmp/tmpyTm0Pa/setuptools-32.3.0
Building a Setuptools egg in /tmp/tmpKOaqof
warning: no files found matching '*' under directory 'setuptools/_vendor'
/tmp/tmpKOaqof/setuptools-32.3.0-py2.7.egg
/tmp/tmpKOaqof/setuptools-32.3.0-py2.7.egg/pkg_resources/__init__.py:184: RuntimeWarning: You have iterated over the result of pkg_resources.parse_version. This is a legacy behavior which is inconsistent with the new version class introduced in setuptools 8.0. In most cases, conversion to a tuple is unnecessary. For comparison of versions, sort the Version instances directly. If you have another use case requiring the tuple, please file a bug with the setuptools project describing that need.
Creating directory '/tmp/build_19264c7456cb5dab7abc2acab3580c08/collective-training-sandbox-fca867c/parts'.
Creating directory '/tmp/build_19264c7456cb5dab7abc2acab3580c08/collective-training-sandbox-fca867c/develop-eggs'.
Generated script '/tmp/build_19264c7456cb5dab7abc2acab3580c08/collective-training-sandbox-fca867c/bin/buildout'.
-----> Run bin/buildout -c heroku.cfg 
Getting distribution for 'ZODB3==3.10.5'.
In file included from src/BTrees/BTreeModuleTemplate.c:394:0,
                 from src/BTrees/_IIBTree.c:34:
src/BTrees/BucketTemplate.c: In function ‘bucket_traverse’:
src/BTrees/BucketTemplate.c:1627:12: warning: variable ‘len’ set but not used [-Wunused-but-set-variable]
     int i, len;
            ^
In file included from src/BTrees/BTreeModuleTemplate.c:394:0,
                 from src/BTrees/_IFBTree.c:34:
src/BTrees/BucketTemplate.c: In function ‘bucket_traverse’:
src/BTrees/BucketTemplate.c:1627:12: warning: variable ‘len’ set but not used [-Wunused-but-set-variable]
     int i, len;
            ^
In file included from src/BTrees/BTreeModuleTemplate.c:394:0,
                 from src/BTrees/_fsBTree.c:83:
src/BTrees/BucketTemplate.c: In function ‘bucket_traverse’:
src/BTrees/BucketTemplate.c:1627:12: warning: variable ‘len’ set but not used [-Wunused-but-set-variable]
     int i, len;
            ^
In file included from src/BTrees/BTreeModuleTemplate.c:394:0,
                 from src/BTrees/_LLBTree.c:36:
src/BTrees/BucketTemplate.c: In function ‘bucket_traverse’:
src/BTrees/BucketTemplate.c:1627:12: warning: variable ‘len’ set but not used [-Wunused-but-set-variable]
     int i, len;
            ^
In file included from src/BTrees/BTreeModuleTemplate.c:394:0,
                 from src/BTrees/_LFBTree.c:36:
src/BTrees/BucketTemplate.c: In function ‘bucket_traverse’:
src/BTrees/BucketTemplate.c:1627:12: warning: variable ‘len’ set but not used [-Wunused-but-set-variable]
     int i, len;
            ^
Got ZODB3 3.10.5.
Getting distribution for 'setuptools==21.0.0'.
warning: no files found matching '*' under directory 'setuptools/_vendor'
warning: no files found matching '*.txt'
Got setuptools 21.0.0.
Getting distribution for 'zc.buildout==2.5.2'.
Got zc.buildout 2.5.2.
Getting distribution for 'zope.interface==3.6.7'.
Got zope.interface 3.6.7.
Getting distribution for 'zope.security==3.7.4'.
Got zope.security 3.7.4.
Getting distribution for 'zope.proxy==3.6.1'.
Got zope.proxy 3.6.1.
Getting distribution for 'zope.i18nmessageid==3.5.3'.
Got zope.i18nmessageid 3.5.3.
Getting distribution for 'zope.container==3.11.2'.
Got zope.container 3.11.2.
Getting distribution for 'initgroups==2.13.0'.
Got initgroups 2.13.0.
Getting distribution for 'Record==2.13.0'.
Got Record 2.13.0.
Getting distribution for 'Products.ZCTextIndex==2.13.5'.
warning: no previously-included files matching '*.dll' found anywhere in distribution
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '*.pyo' found anywhere in distribution
warning: no previously-included files matching '*.so' found anywhere in distribution
src/Products/ZCTextIndex/okascore.c: In function ‘initokascore’:
src/Products/ZCTextIndex/okascore.c:127:12: warning: variable ‘m’ set but not used [-Wunused-but-set-variable]
  PyObject *m;
            ^
Got Products.ZCTextIndex 2.13.5.
Getting distribution for 'Persistence==2.13.2'.
Got Persistence 2.13.2.
Getting distribution for 'MultiMapping==2.13.0'.
src/MultiMapping/_MultiMapping.c:159:2: warning: initialization from incompatible pointer type [enabled by default]
  (inquiry)MM_length,  /*mp_length*/
  ^
src/MultiMapping/_MultiMapping.c:159:2: warning: (near initialization for ‘MM_as_mapping.mp_length’) [enabled by default]
Got MultiMapping 2.13.0.
Getting distribution for 'Missing==2.13.1'.
Got Missing 2.13.1.
Getting distribution for 'ExtensionClass==4.1.2'.
warning: no previously-included files matching '*.dll' found anywhere in distribution
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '*.pyo' found anywhere in distribution
warning: no previously-included files matching '*.so' found anywhere in distribution
Got ExtensionClass 4.1.2.
Getting distribution for 'DocumentTemplate==2.13.2'.
warning: no previously-included files matching '*.dll' found anywhere in distribution
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '*.pyo' found anywhere in distribution
warning: no previously-included files matching '*.so' found anywhere in distribution
src/DocumentTemplate/cDocumentTemplate.c:169:3: warning: initialization from incompatible pointer type [enabled by default]
   (inquiry)InstanceDict_length,  /*mp_length*/
   ^
src/DocumentTemplate/cDocumentTemplate.c:169:3: warning: (near initialization for ‘InstanceDict_as_mapping.mp_length’) [enabled by default]
src/DocumentTemplate/cDocumentTemplate.c:600:2: warning: initialization from incompatible pointer type [enabled by default]
  (inquiry)MM_length,  /*mp_length*/
  ^
src/DocumentTemplate/cDocumentTemplate.c:600:2: warning: (near initialization for ‘MM_as_mapping.mp_length’) [enabled by default]
Got DocumentTemplate 2.13.2.
Getting distribution for 'Acquisition==4.2.2'.
warning: no previously-included files matching '*.dll' found anywhere in distribution
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '*.pyo' found anywhere in distribution
warning: no previously-included files matching '*.so' found anywhere in distribution
Got Acquisition 4.2.2.
Getting distribution for 'AccessControl==3.0.12'.
warning: no files found matching '*.rst'
warning: no previously-included files matching '*.dll' found anywhere in distribution
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '*.pyo' found anywhere in distribution
warning: no previously-included files matching '*.so' found anywhere in distribution
Got AccessControl 3.0.12.
Unused options for buildout: 'unzip'.
Installing instance.
/tmp/build_19264c7456cb5dab7abc2acab3580c08/collective-training-sandbox-fca867c/eggs/setuptools-32.3.0-py2.7.egg/pkg_resources/__init__.py:184: RuntimeWarning: You have iterated over the result of pkg_resources.parse_version. This is a legacy behavior which is inconsistent with the new version class introduced in setuptools 8.0. In most cases, conversion to a tuple is unnecessary. For comparison of versions, sort the Version instances directly. If you have another use case requiring the tuple, please file a bug with the setuptools project describing that need.
Getting distribution for 'Pillow==3.3.0'.
warning: no files found matching '*.sh'
no previously-included directories found matching 'docs/_static'
warning: no previously-included files found matching '.coveragerc'
warning: no previously-included files found matching '.editorconfig'
warning: no previously-included files found matching '.landscape.yaml'
warning: no previously-included files found matching 'appveyor.yml'
warning: no previously-included files found matching 'build_children.sh'
warning: no previously-included files found matching 'tox.ini'
warning: no previously-included files matching '.git*' found anywhere in distribution
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '*.so' found anywhere in distribution
Building using 2 processes
Building using 2 processes
Building using 2 processes
Building using 2 processes
Building using 2 processes
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 357, in _handle_tasks
    debug('task handler got sentinel')
TypeError: 'NoneType' object is not callable
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 330, in _handle_workers
    debug('worker handler exiting')
TypeError: 'NoneType' object is not callable
Exception TypeError: TypeError("'NoneType' object does not support item deletion",) in <Finalize object, dead> ignored
Building using 2 processes
--------------------------------------------------------------------
PIL SETUP SUMMARY
--------------------------------------------------------------------
version      Pillow 3.3.0
platform     linux2 2.7.6 (default, Oct 26 2016, 20:30:19)
             [GCC 4.8.4]
--------------------------------------------------------------------
--- JPEG support available
*** OPENJPEG (JPEG2000) support not available
--- ZLIB (PNG/ZIP) support available
*** LIBIMAGEQUANT support not available
--- LIBTIFF support available
--- FREETYPE2 support available
--- LITTLECMS2 support available
*** WEBP support not available
*** WEBPMUX support not available
--------------------------------------------------------------------
To add a missing option, make sure you have the required
library and headers.
See https://pillow.readthedocs.io/en/latest/installation.html#building-from-source
To check the build, run the selftest.py script.
Got Pillow 3.3.0.
Getting distribution for 'plone.app.mosaic==2.0.0rc1'.
Got plone.app.mosaic 2.0.0rc1.
Getting distribution for 'rapido.plone'.
warning: no files found matching 'docs/LICENCE.*'
Got rapido.plone 1.1.
Getting distribution for 'RelStorage'.
Package libffi was not found in the pkg-config search path.
Perhaps you should add the directory containing `libffi.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libffi' found
Package libffi was not found in the pkg-config search path.
Perhaps you should add the directory containing `libffi.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libffi' found
Package libffi was not found in the pkg-config search path.
Perhaps you should add the directory containing `libffi.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libffi' found
Package libffi was not found in the pkg-config search path.
Perhaps you should add the directory containing `libffi.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libffi' found
Package libffi was not found in the pkg-config search path.
Perhaps you should add the directory containing `libffi.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libffi' found
c/_cffi_backend.c:15:17: fatal error: ffi.h: No such file or directory
 #include <ffi.h>
                 ^
compilation terminated.
error: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
An error occurred when trying to install RelStorage 2.0.0. Look above this message for any errors that were output by easy_install.
While:
  Installing instance.
  Getting distribution for 'RelStorage'.
Error: Couldn't install: RelStorage 2.0.0
 !     Push rejected, failed to compile Plone app.
 !     Push failed
```

**Comment by tkimnguyen** [comment]
Sorry, this is for the wrong Heroku deploy left in my free account!
