### ISSUE TITLE
error with RelStorage push; libffi build error

### ISSUE THREAD

**Issue by tkimnguyen** [collective/training-sandbox#3]
I just tried using the Heroku deploy button at http://plone.fr/essayer-plone with a new free Heroku account.

```-----> Plone app detected
-----> Use build cache
       Cache empty, let's fix that
       Prime with Unified Installer cache
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 58.1M    0 92288    0     0  72078      0  0:14:06  0:00:01  0:14:05 7207858.1M   11 6603k    0     0  2891k      0  0:00:20  0:00:02  0:00:18 6494k58.1M   23 13.5M    0     0  4262k      0  0:00:13  0:00:03  0:00:10 6971k8.1M   32 18.7M    0     0  4179k      0  0:00:14  0:00:04  0:00:10 5763k6 20.9M    0     0  4085k      0  0:00:14  0:00:05  0:00:09 5376k8.1M   42 25.0M    0     0  4085k      0  0:00:14  0:00:06  0:00:08 5115k6 58.1M   46 27.3M    0     0  3851k      0  0:00:15  0:00:07  0:00:08 4290k9 58.1M   49 28.8M    0     0  3569k      0  0:00:16  0:00:08  0:00:08 3119k8.1M   51 30.1M    0     0  3310k      0  0:00:18  0:00:09  0:00:09 2462k   53 31.3M    0     0  3121k      0  0:00:19  0:00:10  0:00:09 2113k   55 32.5M    0     0  2954k      0  0:00:20  0:00:11  0:00:09 1542k.1M   58 33.7M    0     0  2820k      0  0:00:21  0:00:12  0:00:09 1322k 60 34.9M    0     0  2698k      0  0:00:22  0:00:13  0:00:09 1258k62 58.1M   62 36.2M    0     0  2597k      0  0:00:22  0:00:14  0:00:08 1256k 37.5M    0     0  2516k      0  0:00:23  0:00:15  0:00:08 1265k 58.1M   66 38.5M    0     0  2426k      0  0:00:24  0:00:16  0:00:08 1231k68 39.7M    0     0  2357k      0  0:00:25  0:00:17  0:00:08 1223k 58.1M   70 40.8M    0     0  2288k      0  0:00:26  0:00:18  0:00:08 1198k 58.1M   71 41.4M    0     0  2199k      0  0:00:27  0:00:19  0:00:08 1065k 58.1M   71 41.8M    0     0  2113k      0  0:00:28  0:00:20  0:00:08  886k   72 42.2M    0     0  2032k      0  0:00:29  0:00:21  0:00:08  752k   73 42.5M    0     0  1949k      0  0:00:30  0:00:22  0:00:08  556k  73 42.7M    0     0  1879k      0  0:00:31  0:00:23  0:00:08  390k43.0M    0     0  1813k      0  0:00:32  0:00:24  0:00:08  323k1M   74 43.2M    0     0  1750k      0  0:00:34  0:00:25  0:00:09  288k8.1M   74 43.5M    0     0  1697k      0  0:00:35  0:00:26  0:00:09  269k   75 43.8M    0     0  1645k      0  0:00:36  0:00:27  0:00:09  271k  75 44.0M    0     0  1595k      0  0:00:37  0:00:28  0:00:09  269k   76 44.2M    0     0  1547k      0  0:00:38  0:00:29  0:00:09  250k   76 44.4M    0     0  1502k      0  0:00:39  0:00:30  0:00:09  238k.1M   76 44.6M    0     0  1461k      0  0:00:40  0:00:31  0:00:09  227k.1M   77 44.9M    0     0  1424k      0  0:00:41  0:00:32  0:00:09  230kM   77 45.3M    0     0  1391k      0  0:00:42  0:00:33  0:00:09  250k1M   78 45.6M    0     0  1364k      0  0:00:43  0:00:34  0:00:09  293k 58.1M   79 46.1M    0     0  1339k      0  0:00:44  0:00:35  0:00:09  345k   79 46.4M    0     0  1312k      0  0:00:45  0:00:36  0:00:09  372k0 58.1M   80 46.7M    0     0  1285k      0  0:00:46  0:00:37  0:00:09  375k0 47.1M    0     0  1259k      0  0:00:47  0:00:38  0:00:09  373k   81 47.4M    0     0  1237k      0  0:00:48  0:00:39  0:00:09  372k82 47.8M    0     0  1217k      0  0:00:48  0:00:40  0:00:08  362k   83 48.3M    0     0  1199k      0  0:00:49  0:00:41  0:00:08  385k.1M   84 48.9M    0     0  1185k      0  0:00:50  0:00:42  0:00:08  441k 85 49.5M    0     0  1171k      0  0:00:50  0:00:43  0:00:07  493k  86 50.1M    0     0  1158k      0  0:00:51  0:00:44  0:00:07  539k8.1M   87 50.7M    0     0  1147k      0  0:00:51  0:00:45  0:00:06  582k 58.1M   88 51.2M    0     0  1134k      0  0:00:52  0:00:46  0:00:06  594k8 58.1M   88 51.6M    0     0  1119k      0  0:00:53  0:00:47  0:00:06  560k 58.1M   89 52.0M    0     0  1104k      0  0:00:53  0:00:48  0:00:05  519k9 58.1M   89 52.3M    0     0  1087k      0  0:00:54  0:00:49  0:00:05  454k 58.1M   90 52.6M    0     0  1071k      0  0:00:55  0:00:50  0:00:05  390k.1M   91 52.9M    0     0  1057k      0  0:00:56  0:00:51  0:00:05  353k1 53.3M    0     0  1044k      0  0:00:57  0:00:52  0:00:05  338k1M   92 53.6M    0     0  1031k      0  0:00:57  0:00:53  0:00:04  331k58.1M   92 54.0M    0     0  1020k      0  0:00:58  0:00:54  0:00:04  352k4M    0     0  1009k      0  0:00:59  0:00:55  0:00:04  377k58.1M   94 54.9M    0     0   999k      0  0:00:59  0:00:56  0:00:03  402k55.4M    0     0   991k      0  0:01:00  0:00:57  0:00:03  439k.1M   96 56.0M    0     0   985k      0  0:01:00  0:00:58  0:00:02  496k97 58.1M   97 56.9M    0     0   983k      0  0:01:00  0:00:59  0:00:01  592k.1M  100 58.1M    0     0   989k      0  0:01:00  0:01:00 --:--:--  771k
       Unpacking Installer
       Unpacking Installer cache
       Moving cache eggs to build directory
       Clean up Installer files
-----> Read BUILDOUT_CFG from env vars, or use default
       Using default: heroku.cfg
-----> Read BUILDOUT_VERBOSITY from env vars, or use default
       Use default buildout verbosity
-----> Read BOOTSTRAP_PY_URL from env vars, or use default
       Use default bootstrap.py: http://downloads.buildout.org/2/bootstrap.py
-----> Bootstrap buildout
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
curl: (6) Could not resolve host: L
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="https://bootstrap.pypa.io/bootstrap-buildout.py">here</a>.</p>
<hr>
<address>Apache Server at downloads.buildout.org Port 80</address>
</body></html>
Downloading https://pypi.io/packages/source/s/setuptools/setuptools-33.1.1.zip
Extracting in /tmp/tmpGFLuEN
Now working in /tmp/tmpGFLuEN/setuptools-33.1.1
Building a Setuptools egg in /tmp/tmpozfQUV
warning: no files found matching '*' under directory 'setuptools/_vendor'
/tmp/tmpozfQUV/setuptools-33.1.1-py2.7.egg
/tmp/tmpozfQUV/setuptools-33.1.1-py2.7.egg/pkg_resources/__init__.py:184: RuntimeWarning: You have iterated over the result of pkg_resources.parse_version. This is a legacy behavior which is inconsistent with the new version class introduced in setuptools 8.0. In most cases, conversion to a tuple is unnecessary. For comparison of versions, sort the Version instances directly. If you have another use case requiring the tuple, please file a bug with the setuptools project describing that need.
Creating directory '/tmp/build_99703c3aa246ad1217e3973f0ceca5f0/collective-training-sandbox-fca867c/parts'.
Creating directory '/tmp/build_99703c3aa246ad1217e3973f0ceca5f0/collective-training-sandbox-fca867c/develop-eggs'.
Generated script '/tmp/build_99703c3aa246ad1217e3973f0ceca5f0/collective-training-sandbox-fca867c/bin/buildout'.
-----> Run bin/buildout -c heroku.cfg 
Getting distribution for 'ZODB3==3.10.5'.
In file included from src/BTrees/BTreeModuleTemplate.c:394:0,
                 from src/BTrees/_IIBTree.c:34:
src/BTrees/BucketTemplate.c: In function ‘bucket_traverse’:
src/BTrees/BucketTemplate.c:1627:12: warning: variable ‘len’ set but not used [-Wunused-but-set-variable]
     int i, len;
            ^
In file included from src/BTrees/BTreeModuleTemplate.c:394:0,
                 from src/BTrees/_IFBTree.c:34:
src/BTrees/BucketTemplate.c: In function ‘bucket_traverse’:
src/BTrees/BucketTemplate.c:1627:12: warning: variable ‘len’ set but not used [-Wunused-but-set-variable]
     int i, len;
            ^
In file included from src/BTrees/BTreeModuleTemplate.c:394:0,
                 from src/BTrees/_fsBTree.c:83:
src/BTrees/BucketTemplate.c: In function ‘bucket_traverse’:
src/BTrees/BucketTemplate.c:1627:12: warning: variable ‘len’ set but not used [-Wunused-but-set-variable]
     int i, len;
            ^
In file included from src/BTrees/BTreeModuleTemplate.c:394:0,
                 from src/BTrees/_LLBTree.c:36:
src/BTrees/BucketTemplate.c: In function ‘bucket_traverse’:
src/BTrees/BucketTemplate.c:1627:12: warning: variable ‘len’ set but not used [-Wunused-but-set-variable]
     int i, len;
            ^
In file included from src/BTrees/BTreeModuleTemplate.c:394:0,
                 from src/BTrees/_LFBTree.c:36:
src/BTrees/BucketTemplate.c: In function ‘bucket_traverse’:
src/BTrees/BucketTemplate.c:1627:12: warning: variable ‘len’ set but not used [-Wunused-but-set-variable]
     int i, len;
            ^
Got ZODB3 3.10.5.
Getting distribution for 'setuptools==21.0.0'.
warning: no files found matching '*' under directory 'setuptools/_vendor'
warning: no files found matching '*.txt'
Got setuptools 21.0.0.
Getting distribution for 'zc.buildout==2.5.2'.
Got zc.buildout 2.5.2.
Getting distribution for 'zope.interface==3.6.7'.
Got zope.interface 3.6.7.
Getting distribution for 'zope.security==3.7.4'.
Got zope.security 3.7.4.
Getting distribution for 'zope.proxy==3.6.1'.
Got zope.proxy 3.6.1.
Getting distribution for 'zope.i18nmessageid==3.5.3'.
Got zope.i18nmessageid 3.5.3.
Getting distribution for 'zope.container==3.11.2'.
Got zope.container 3.11.2.
Getting distribution for 'initgroups==2.13.0'.
Got initgroups 2.13.0.
Getting distribution for 'Record==2.13.0'.
Got Record 2.13.0.
Getting distribution for 'Products.ZCTextIndex==2.13.5'.
warning: no previously-included files matching '*.dll' found anywhere in distribution
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '*.pyo' found anywhere in distribution
warning: no previously-included files matching '*.so' found anywhere in distribution
src/Products/ZCTextIndex/okascore.c: In function ‘initokascore’:
src/Products/ZCTextIndex/okascore.c:127:12: warning: variable ‘m’ set but not used [-Wunused-but-set-variable]
  PyObject *m;
            ^
Got Products.ZCTextIndex 2.13.5.
Getting distribution for 'Persistence==2.13.2'.
Got Persistence 2.13.2.
Getting distribution for 'MultiMapping==2.13.0'.
src/MultiMapping/_MultiMapping.c:159:2: warning: initialization from incompatible pointer type [enabled by default]
  (inquiry)MM_length,  /*mp_length*/
  ^
src/MultiMapping/_MultiMapping.c:159:2: warning: (near initialization for ‘MM_as_mapping.mp_length’) [enabled by default]
Got MultiMapping 2.13.0.
Getting distribution for 'Missing==2.13.1'.
Got Missing 2.13.1.
Getting distribution for 'ExtensionClass==4.1.2'.
warning: no previously-included files matching '*.dll' found anywhere in distribution
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '*.pyo' found anywhere in distribution
warning: no previously-included files matching '*.so' found anywhere in distribution
Got ExtensionClass 4.1.2.
Getting distribution for 'DocumentTemplate==2.13.2'.
warning: no previously-included files matching '*.dll' found anywhere in distribution
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '*.pyo' found anywhere in distribution
warning: no previously-included files matching '*.so' found anywhere in distribution
src/DocumentTemplate/cDocumentTemplate.c:169:3: warning: initialization from incompatible pointer type [enabled by default]
   (inquiry)InstanceDict_length,  /*mp_length*/
   ^
src/DocumentTemplate/cDocumentTemplate.c:169:3: warning: (near initialization for ‘InstanceDict_as_mapping.mp_length’) [enabled by default]
src/DocumentTemplate/cDocumentTemplate.c:600:2: warning: initialization from incompatible pointer type [enabled by default]
  (inquiry)MM_length,  /*mp_length*/
  ^
src/DocumentTemplate/cDocumentTemplate.c:600:2: warning: (near initialization for ‘MM_as_mapping.mp_length’) [enabled by default]
Got DocumentTemplate 2.13.2.
Getting distribution for 'Acquisition==4.2.2'.
warning: no previously-included files matching '*.dll' found anywhere in distribution
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '*.pyo' found anywhere in distribution
warning: no previously-included files matching '*.so' found anywhere in distribution
Got Acquisition 4.2.2.
Getting distribution for 'AccessControl==3.0.12'.
warning: no files found matching '*.rst'
warning: no previously-included files matching '*.dll' found anywhere in distribution
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '*.pyo' found anywhere in distribution
warning: no previously-included files matching '*.so' found anywhere in distribution
Got AccessControl 3.0.12.
Unused options for buildout: 'unzip'.
Installing instance.
/tmp/build_99703c3aa246ad1217e3973f0ceca5f0/collective-training-sandbox-fca867c/eggs/setuptools-33.1.1-py2.7.egg/pkg_resources/__init__.py:184: RuntimeWarning: You have iterated over the result of pkg_resources.parse_version. This is a legacy behavior which is inconsistent with the new version class introduced in setuptools 8.0. In most cases, conversion to a tuple is unnecessary. For comparison of versions, sort the Version instances directly. If you have another use case requiring the tuple, please file a bug with the setuptools project describing that need.
Getting distribution for 'Pillow==3.3.0'.
warning: no files found matching '*.sh'
no previously-included directories found matching 'docs/_static'
warning: no previously-included files found matching '.coveragerc'
warning: no previously-included files found matching '.editorconfig'
warning: no previously-included files found matching '.landscape.yaml'
warning: no previously-included files found matching 'appveyor.yml'
warning: no previously-included files found matching 'build_children.sh'
warning: no previously-included files found matching 'tox.ini'
warning: no previously-included files matching '.git*' found anywhere in distribution
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '*.so' found anywhere in distribution
Building using 2 processes
Building using 2 processes
Building using 2 processes
Building using 2 processes
Building using 2 processes
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 357, in _handle_tasks
    debug('task handler got sentinel')
TypeError: 'NoneType' object is not callable
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 330, in _handle_workers
    debug('worker handler exiting')
TypeError: 'NoneType' object is not callable
Exception TypeError: TypeError("'NoneType' object does not support item deletion",) in <Finalize object, dead> ignored
Building using 2 processes
--------------------------------------------------------------------
PIL SETUP SUMMARY
--------------------------------------------------------------------
version      Pillow 3.3.0
platform     linux2 2.7.6 (default, Oct 26 2016, 20:30:19)
             [GCC 4.8.4]
--------------------------------------------------------------------
--- JPEG support available
*** OPENJPEG (JPEG2000) support not available
--- ZLIB (PNG/ZIP) support available
*** LIBIMAGEQUANT support not available
--- LIBTIFF support available
--- FREETYPE2 support available
--- LITTLECMS2 support available
*** WEBP support not available
*** WEBPMUX support not available
--------------------------------------------------------------------
To add a missing option, make sure you have the required
library and headers.
See https://pillow.readthedocs.io/en/latest/installation.html#building-from-source
To check the build, run the selftest.py script.
Got Pillow 3.3.0.
Getting distribution for 'plone.app.mosaic==2.0.0rc1'.
Got plone.app.mosaic 2.0.0rc1.
Getting distribution for 'rapido.plone'.
warning: no files found matching 'docs/LICENCE.*'
Got rapido.plone 1.1.
Getting distribution for 'RelStorage'.
Package libffi was not found in the pkg-config search path.
Perhaps you should add the directory containing `libffi.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libffi' found
Package libffi was not found in the pkg-config search path.
Perhaps you should add the directory containing `libffi.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libffi' found
Package libffi was not found in the pkg-config search path.
Perhaps you should add the directory containing `libffi.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libffi' found
Package libffi was not found in the pkg-config search path.
Perhaps you should add the directory containing `libffi.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libffi' found
Package libffi was not found in the pkg-config search path.
Perhaps you should add the directory containing `libffi.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libffi' found
c/_cffi_backend.c:15:17: fatal error: ffi.h: No such file or directory
 #include <ffi.h>
                 ^
compilation terminated.
error: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
An error occurred when trying to install RelStorage 2.0.0. Look above this message for any errors that were output by easy_install.
While:
  Installing instance.
  Getting distribution for 'RelStorage'.
Error: Couldn't install: RelStorage 2.0.0
 !     Push rejected, failed to compile Plone app.
 !     Push failed```

**Comment by ebrehault** [comment]
RelStorage had to be pinned to 1.6.3
