### ISSUE TITLE
zc.buildout version conflict when building app

### ISSUE THREAD

**Issue by fulv** [collective/training-sandbox#9]
I just tried creating the heroku build, and got this error:

```


-----> Plone app detected

-----> Use build cache

       Cache empty, let's fix that

       Prime with Unified Installer cache

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current

                                 Dload  Upload   Total   Spent    Left  Speed

204k 9 57.9M    9 5504k    0     0  1284k      0  0:00:46  0:00:04  0:00:42 1934k

       Unpacking Installer

       Unpacking Installer cache

       Moving cache eggs to build directory

       Clean up Installer files

-----> Read BUILDOUT_CFG from env vars, or use default

       Using default: heroku.cfg

-----> Read BUILDOUT_VERBOSITY from env vars, or use default

       Use default buildout verbosity

-----> Read BOOTSTRAP_PY_URL from env vars, or use default

       Use default bootstrap.py: http://downloads.buildout.org/2/bootstrap.py

-----> Bootstrap buildout

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current

                                 Dload  Upload   Total   Spent    Left  Speed

curl: (6) Could not resolve host: L

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">

<html><head>

<title>301 Moved Permanently</title>

</head><body>

<h1>Moved Permanently</h1>

<p>The document has moved <a href="https://bootstrap.pypa.io/bootstrap-buildout.py">here</a>.</p>

<hr>

<address>Apache Server at downloads.buildout.org Port 80</address>

</body></html>

ez_setup.py is deprecated and when using it setuptools will be pinned to 33.1.1 since it's the last version that supports setuptools self upgrade/installation, check https://github.com/pypa/setuptools/issues/581 for more info; use pip to install setuptools

Downloading https://pypi.io/packages/source/s/setuptools/setuptools-33.1.1.zip

Extracting in /tmp/tmpMijzNB

Now working in /tmp/tmpMijzNB/setuptools-33.1.1

Building a Setuptools egg in /tmp/tmpyt2yoq

warning: no files found matching '*' under directory 'setuptools/_vendor'

/tmp/tmpyt2yoq/setuptools-33.1.1-py2.7.egg

/tmp/tmpyt2yoq/setuptools-33.1.1-py2.7.egg/pkg_resources/__init__.py:184: RuntimeWarning: You have iterated over the result of pkg_resources.parse_version. This is a legacy behavior which is inconsistent with the new version class introduced in setuptools 8.0. In most cases, conversion to a tuple is unnecessary. For comparison of versions, sort the Version instances directly. If you have another use case requiring the tuple, please file a bug with the setuptools project describing that need.

no previously-included directories found matching 'doc'

no previously-included directories found matching 'old-tutorial'

Creating directory '/tmp/build_af713b6ba19f178d97c61a616889ca7d/collective-training-sandbox-b537dda/parts'.

Creating directory '/tmp/build_af713b6ba19f178d97c61a616889ca7d/collective-training-sandbox-b537dda/develop-eggs'.

Generated script '/tmp/build_af713b6ba19f178d97c61a616889ca7d/collective-training-sandbox-b537dda/bin/buildout'.

-----> Run bin/buildout -c heroku.cfg 

Getting distribution for 'ZODB3==3.10.7'.

In file included from src/BTrees/BTreeModuleTemplate.c:394:0,

                 from src/BTrees/_IIBTree.c:34:

src/BTrees/BucketTemplate.c: In function ‘bucket_traverse’:

src/BTrees/BucketTemplate.c:1627:12: warning: variable ‘len’ set but not used [-Wunused-but-set-variable]

     int i, len;

            ^

In file included from src/BTrees/BTreeModuleTemplate.c:394:0,

                 from src/BTrees/_IFBTree.c:34:

src/BTrees/BucketTemplate.c: In function ‘bucket_traverse’:

src/BTrees/BucketTemplate.c:1627:12: warning: variable ‘len’ set but not used [-Wunused-but-set-variable]

     int i, len;

            ^

In file included from src/BTrees/BTreeModuleTemplate.c:394:0,

                 from src/BTrees/_fsBTree.c:83:

src/BTrees/BucketTemplate.c: In function ‘bucket_traverse’:

src/BTrees/BucketTemplate.c:1627:12: warning: variable ‘len’ set but not used [-Wunused-but-set-variable]

     int i, len;

            ^

In file included from src/BTrees/BTreeModuleTemplate.c:394:0,

                 from src/BTrees/_LLBTree.c:36:

src/BTrees/BucketTemplate.c: In function ‘bucket_traverse’:

src/BTrees/BucketTemplate.c:1627:12: warning: variable ‘len’ set but not used [-Wunused-but-set-variable]

     int i, len;

            ^

In file included from src/BTrees/BTreeModuleTemplate.c:394:0,

                 from src/BTrees/_LFBTree.c:36:

src/BTrees/BucketTemplate.c: In function ‘bucket_traverse’:

src/BTrees/BucketTemplate.c:1627:12: warning: variable ‘len’ set but not used [-Wunused-but-set-variable]

     int i, len;

            ^

Got ZODB3 3.10.7.

Getting distribution for 'zc.buildout==2.9.4'.

no previously-included directories found matching 'doc'

no previously-included directories found matching 'old-tutorial'

While:

  Installing.

  Getting section precompile.

  Initializing section precompile.

  Getting option precompile:eggs.

  Getting section instance.

  Initializing section instance.

  Installing recipe plone.recipe.zope2instance.

  Getting distribution for 'zc.buildout==2.9.4'.

An internal error occurred due to a bug in either zc.buildout or in a

recipe being used:

Traceback (most recent call last):

  File "/tmp/build_af713b6ba19f178d97c61a616889ca7d/collective-training-sandbox-b537dda/eggs/zc.buildout-2.9.5-py2.7.egg/zc/buildout/buildout.py", line 2123, in main

    getattr(buildout, command)(args)

  File "/tmp/build_af713b6ba19f178d97c61a616889ca7d/collective-training-sandbox-b537dda/eggs/zc.buildout-2.9.5-py2.7.egg/zc/buildout/buildout.py", line 680, in install

    [self[part]['recipe'] for part in install_parts]

  File "/tmp/build_af713b6ba19f178d97c61a616889ca7d/collective-training-sandbox-b537dda/eggs/zc.buildout-2.9.5-py2.7.egg/zc/buildout/buildout.py", line 1274, in __getitem__

    options._initialize()

  File "/tmp/build_af713b6ba19f178d97c61a616889ca7d/collective-training-sandbox-b537dda/eggs/zc.buildout-2.9.5-py2.7.egg/zc/buildout/buildout.py", line 1372, in _initialize

    self._dosub(k, v)

  File "/tmp/build_af713b6ba19f178d97c61a616889ca7d/collective-training-sandbox-b537dda/eggs/zc.buildout-2.9.5-py2.7.egg/zc/buildout/buildout.py", line 1427, in _dosub

    v = '$$'.join([self._sub(s, seen) for s in v.split('$$')])

  File "/tmp/build_af713b6ba19f178d97c61a616889ca7d/collective-training-sandbox-b537dda/eggs/zc.buildout-2.9.5-py2.7.egg/zc/buildout/buildout.py", line 1491, in _sub

    v = self.buildout[section].get(option, None, seen)

  File "/tmp/build_af713b6ba19f178d97c61a616889ca7d/collective-training-sandbox-b537dda/eggs/zc.buildout-2.9.5-py2.7.egg/zc/buildout/buildout.py", line 1274, in __getitem__

    options._initialize()

  File "/tmp/build_af713b6ba19f178d97c61a616889ca7d/collective-training-sandbox-b537dda/eggs/zc.buildout-2.9.5-py2.7.egg/zc/buildout/buildout.py", line 1382, in _initialize

    self.initialize()

  File "/tmp/build_af713b6ba19f178d97c61a616889ca7d/collective-training-sandbox-b537dda/eggs/zc.buildout-2.9.5-py2.7.egg/zc/buildout/buildout.py", line 1388, in initialize

    recipe_class = _install_and_load(reqs, 'zc.buildout', entry, buildout)

  File "/tmp/build_af713b6ba19f178d97c61a616889ca7d/collective-training-sandbox-b537dda/eggs/zc.buildout-2.9.5-py2.7.egg/zc/buildout/buildout.py", line 1338, in _install_and_load

    allow_hosts=buildout._allow_hosts

  File "/tmp/build_af713b6ba19f178d97c61a616889ca7d/collective-training-sandbox-b537dda/eggs/zc.buildout-2.9.5-py2.7.egg/zc/buildout/easy_install.py", line 913, in install

    return installer.install(specs, working_set)

  File "/tmp/build_af713b6ba19f178d97c61a616889ca7d/collective-training-sandbox-b537dda/eggs/zc.buildout-2.9.5-py2.7.egg/zc/buildout/easy_install.py", line 714, in install

    for dist in self._get_dist(req, ws):

  File "/tmp/build_af713b6ba19f178d97c61a616889ca7d/collective-training-sandbox-b537dda/eggs/zc.buildout-2.9.5-py2.7.egg/zc/buildout/easy_install.py", line 570, in _get_dist

    dist = self._env.best_match(requirement, ws)

  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1111, in best_match

    dist = working_set.find(req)

  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 715, in find

    raise VersionConflict(dist, req)

VersionConflict: (zc.buildout 2.9.5 (/tmp/build_af713b6ba19f178d97c61a616889ca7d/collective-training-sandbox-b537dda/eggs/zc.buildout-2.9.5-py2.7.egg), Requirement.parse('zc.buildout==2.9.4'))

 !     Push rejected, failed to compile Plone app.

 !     Push failed

```

**Comment by jean** [comment]
Still broken, @ebrehault ?

**Comment by ebrehault** [comment]
Fixed by https://github.com/collective/training-sandbox/commit/8839db851a82bfbefa5abdb46089fd10ed835a23
